### PR TITLE
Added GDM entry file for way-cooler

### LINKED ISSUE #154: Add way-cooler to gdm
I installed the AUR package and way-cooler is not in gdm's window manager list.

### PR DESCRIPTION
**Pull request by starfys**
Resolves #154

### CODE REVIEW

**Comment by starfys** [comment]
Note that for Arch/AUR packaging, this file should be stored as /usr/share/xsessions/way-cooler.desktop

**Comment by Timidger** [comment]
Haven't had a chance to test this yet, but I believe the command to be executed should be `dbus-launch --exit-with-session way-cooler`. This will properly launch the dbus server for Way Cooler when ran headless (Most X WM's already start this, which is why this is unnecessary when testing within X)

**Comment by starfys** [comment]
Added the line for DBUS. TryExec stays the same because it's used to check if way-cooler is installed. I installed GDM and tested the session using the new conf file. way-cooler starts, but 2 mouse pointers are shown. One of them is from GDM and the other is for way-cooler.  I logged into a Weston session from GDM and got the same mouse bug there.

**Comment by starfys** [comment]
This issue seems related to SirCmpwn/sway#759

**Comment by starfys** [comment]
After changing the location of way-cooler.desktop from ```/usr/share/xsessions/way-cooler.desktop``` to ```/usr/share/wayland-sessions/way-cooler.desktop```, there was no change. However, if I Ctrl+Alt+F2 to a TTY and then Ctrl+Alt+F7 back to way-cooler, the hardware cursor from GDM disappears.

**Comment by Timidger** [comment]
Hm, yes I'm getting the same issue on my testing. From the linked discussion on sway, it looks this is a gdm bug? I know that this bug appeared when using light-dm on Ubuntu, I haven't had time to test gdm (borked Ubuntu trying to install gdm, somehow -_-). Hopefully there's some magic we can do to tell gdm to not do that. Is gdm running Way Cooler in an embedded X environment? Is that why two pointers are showing?

**Comment by starfys** [comment]
It's not running it within an X session. At least on Arch, GDM uses Wayland as its backend by default.

**Comment by Timidger** [comment]
After moving `way-cooler.desktop` to `/usr/share/wayland-sessions/` it started working flawlessly for me on my fedora machine using lightdm. I'll retest with gdm and see if I can reproduce the weird cursor issue.

**Pull request merged**
