### PR TITLE
Made it more clear we link a video

### PR DESCRIPTION
**Pull request by Timidger**

### CODE REVIEW

**Comment by SnirkImmington** [comment]
You took a screenshot halfway through the video. Maybe it's a better frame than the one we had before but it looks hideous.

**Comment by Timidger** [comment]
Yeah, that was a concern I had about it. I'll can attempt to edit it later so we can keep the frame but make it look like it's at the beginning of the video. Should I do that?

**Comment by SnirkImmington** [comment]
You could remove the alt image altogether, give me a lovely "Firefox has prevented the outdated plugin 'Adobe Flash' from running" box in the readme instead 😛

**Comment by Timidger** [comment]
Though to be honest I don't think my change looks that hideous, I think it makes it clearer that it's a video. If it was literally an image that would be hideous but I think this is an ok compromise.

**Comment by SnirkImmington** [comment]
Okay, I suppose it's not _that_ hideous.

**Pull request merged**
